version: "3.8"
services:
  client:
    build:
      context: .
    container_name: react-okta-scope-auth
    image: react-okta-scope-auth-image:latest
    ports: 
      - '3000:3000'
    volumes: 
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
